import { supabase } from './supabaseClient';

export interface Declaration {
    id: string;
    // Client Information
    client_id?: string;
    client_email?: string;
    client_phone?: string;
    // Insured Information
    insured_name: string;
    secondary_insured_name?: string;
    // Addresses
    mailing_address: string;
    property_location: string;
    // Policy Metadata
    policy_number: string;
    date_issued: string;
    policy_period_start: string;
    policy_period_end: string;
    renewal_date: string;
    // Property Details
    year_built: number;
    occupancy: string;
    number_of_units: number;
    construction_type: string;
    deductible: string;
    // Coverage Limits
    limit_dwelling: string;
    limit_other_structures: string;
    limit_personal_property: string;
    limit_fair_rental_value: string;
    limit_ordinance_or_law: string;
    limit_debris_removal: string;
    limit_extended_dwelling_coverage: string;
    limit_dwelling_replacement_cost: string;
    limit_inflation_guard: string;
    limit_personal_property_replacement_cost: string;
    limit_fences: string;
    limit_permitted_incidental_occupancy: string;
    limit_plants_shrubs_trees: string;
    limit_outdoor_radio_tv_equipment: string;
    limit_awnings: string;
    limit_signs: string;
    // Special Coverage
    limit_actual_cash_value_coverage?: string;
    limit_replacement_cost_coverage?: string;
    limit_building_code_upgrade_coverage?: string;
    limit_extended_replacement_cost_coverage?: string;
    limit_guaranteed_replacement_cost_coverage?: string;
    // Flags (Checkboxes)
    cb_fire_lightning_smoke_damage: boolean;
    cb_extended_coverages: boolean;
    cb_vandalism_malicious_mischief: boolean;
    // Wildfire
    wildfire_risk_score_l1?: string;
    wildfire_risk_score_l2?: string;
    wildfire_premium: string;
    wildfire_score_classification_l1?: string;
    wildfire_score_classification_l2?: string;
    // Premium
    total_annual_premium: string;
    // Broker
    broker_name: string;
    broker_address: string;
    broker_phone_number: string;
    // Mortgagees
    mortgagee_1_name?: string;
    mortgagee_1_address?: string;
    mortgagee_1_code?: string;
    mortgagee_2_name?: string;
    mortgagee_2_address?: string;
    mortgagee_2_code?: string;
    // DIC (Difference in Conditions)
    dic_company?: string; // Company name or "None"

    // System Fields
    status: 'Pending Review' | 'Approved' | 'Rejected' | 'Incomplete';
    flags: string[]; // For UI display
}

export async function submitDeclaration(data: any) {
    console.log('Submitting declaration:', data);
    return { success: true };
}

const mockData: Declaration[] = [
    {
        id: '1',
        client_id: 'client-001',
        client_email: 'johndoe@email.com',
        client_phone: '(555) 234-5678',
        insured_name: 'John & Jane Doe',
        secondary_insured_name: 'Jane Doe',
        mailing_address: '123 Maple St, Springfield, IL 62704',
        property_location: '123 Maple St, Springfield, IL 62704',
        policy_number: 'HO-983274-23',
        date_issued: '2023-10-01',
        policy_period_start: '2023-10-15',
        policy_period_end: '2024-10-15',
        renewal_date: '2024-10-15',
        year_built: 1985,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Frame',
        deductible: '$2,500',
        limit_dwelling: '$450,000',
        limit_other_structures: '$45,000',
        limit_personal_property: '$225,000',
        limit_fair_rental_value: '$90,000',
        limit_ordinance_or_law: '$45,000',
        limit_debris_removal: '$22,500',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$5,000',
        limit_permitted_incidental_occupancy: '$2,500',
        limit_plants_shrubs_trees: '$10,000',
        limit_outdoor_radio_tv_equipment: '$1,500',
        limit_awnings: '$2,500',
        limit_signs: '$1,000',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$150',
        total_annual_premium: '$1,850',
        broker_name: 'Trusty Insurance Agency',
        broker_address: '456 Oak Ave, Springfield, IL',
        broker_phone_number: '(555) 123-4567',
        mortgagee_1_name: 'First National Bank',
        mortgagee_1_address: 'PO Box 999, Wilmington, DE',
        mortgagee_1_code: 'FNB-001',
        dic_company: "Lloyd's of London",
        status: 'Pending Review',
        flags: ['High Value', 'Wildfire Zone'],
        wildfire_risk_score_l1: 'Moderate'
    },
    {
        id: '2',
        insured_name: 'Robert Smith',
        mailing_address: '789 Pine Ln, Boulder, CO 80302',
        property_location: '789 Pine Ln, Boulder, CO 80302',
        policy_number: 'HO-112233-44',
        date_issued: '2023-09-15',
        policy_period_start: '2023-09-20',
        policy_period_end: '2024-09-20',
        renewal_date: '2024-09-20',
        year_built: 2010,
        occupancy: 'Secondary',
        number_of_units: 1,
        construction_type: 'Masonry',
        deductible: '$5,000',
        limit_dwelling: '$850,000',
        limit_other_structures: '$85,000',
        limit_personal_property: '$425,000',
        limit_fair_rental_value: '$170,000',
        limit_ordinance_or_law: '$85,000',
        limit_debris_removal: '$42,500',
        limit_extended_dwelling_coverage: '50%',
        limit_dwelling_replacement_cost: 'Guaranteed',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$15,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$25,000',
        limit_outdoor_radio_tv_equipment: '$3,000',
        limit_awnings: '$5,000',
        limit_signs: '$2,000',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: false,
        wildfire_premium: '$850',
        total_annual_premium: '$4,200',
        broker_name: 'Mountain View Brokers',
        broker_address: '1000 Summit Blvd, Denver, CO',
        broker_phone_number: '(303) 555-9876',
        mortgagee_1_name: 'Wells Fargo',
        mortgagee_1_address: 'Des Moines, IA',
        status: 'Approved',
        flags: ['Secondary Residence'],
    },
    {
        id: '3',
        insured_name: 'Alice Cooper',
        mailing_address: '22 Acacia Ave, London',
        property_location: '555 Hollywood Blvd, Los Angeles, CA 90028',
        policy_number: 'HO-666777-88',
        date_issued: '2023-11-01',
        policy_period_start: '2023-11-01',
        policy_period_end: '2024-11-01',
        renewal_date: '2024-11-01',
        year_built: 1955,
        occupancy: 'Primary Residence',
        number_of_units: 2,
        construction_type: 'Frame',
        deductible: '$1,000',
        limit_dwelling: '$600,000',
        limit_other_structures: '$20,000',
        limit_personal_property: '$300,000',
        limit_fair_rental_value: '$50,000',
        limit_ordinance_or_law: '$10,000',
        limit_debris_removal: '$10,000',
        limit_extended_dwelling_coverage: 'None',
        limit_dwelling_replacement_cost: 'Standard',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'ACV Only',
        limit_fences: '$2,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$5,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: false,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$200',
        total_annual_premium: '$2,100',
        broker_name: 'Rock Star Insure',
        broker_address: 'Sunset Strip, CA',
        broker_phone_number: '(323) 555-1111',
        status: 'Rejected',
        flags: ['Old Construction', 'Missing Info'],
    },
    {
        id: '4',
        insured_name: 'Elena Fisher',
        mailing_address: '88 Ocean Dr, Miami, FL 33139',
        property_location: '88 Ocean Dr, Miami, FL 33139',
        policy_number: 'HO-334455-66',
        date_issued: '2023-08-20',
        policy_period_start: '2023-09-01',
        policy_period_end: '2024-09-01',
        renewal_date: '2024-09-01',
        year_built: 2018,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Concrete',
        deductible: '$10,000',
        limit_dwelling: '$1,200,000',
        limit_other_structures: '$120,000',
        limit_personal_property: '$600,000',
        limit_fair_rental_value: '$240,000',
        limit_ordinance_or_law: '$120,000',
        limit_debris_removal: '$60,000',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$25,000',
        limit_permitted_incidental_occupancy: '$5,000',
        limit_plants_shrubs_trees: '$50,000',
        limit_outdoor_radio_tv_equipment: '$5,000',
        limit_awnings: '$10,000',
        limit_signs: '$5,000',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$6,500',
        broker_name: 'Coastal Insurance Group',
        broker_address: '101 Biscayne Blvd, Miami, FL',
        broker_phone_number: '(305) 555-2222',
        mortgagee_1_name: 'Chase Bank',
        status: 'Approved',
        flags: ['High Premium', 'Windstorm'],
    },
    {
        id: '5',
        insured_name: 'David & Sarah Connor',
        mailing_address: '404 Error Rd, Seattle, WA 98101',
        property_location: '404 Error Rd, Seattle, WA 98101',
        policy_number: 'HO-500500-00',
        date_issued: '2023-12-01',
        policy_period_start: '2023-12-15',
        policy_period_end: '2024-12-15',
        renewal_date: '2024-12-15',
        year_built: 2020,
        occupancy: 'Tenant',
        number_of_units: 4,
        construction_type: 'Mixed',
        deductible: '$500',
        limit_dwelling: '$300,000',
        limit_other_structures: '$0',
        limit_personal_property: '$100,000',
        limit_fair_rental_value: '$0',
        limit_ordinance_or_law: '$0',
        limit_debris_removal: '$5,000',
        limit_extended_dwelling_coverage: 'None',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$0',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$0',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$50',
        total_annual_premium: '$450',
        broker_name: 'Urban Living Ins',
        broker_address: 'Seattle, WA',
        broker_phone_number: '(206) 555-3333',
        status: 'Incomplete',
        flags: [],
    },
    {
        id: '6',
        insured_name: 'James Wilson',
        mailing_address: '5501 Lakeview Dr, Kirkland, WA 98033',
        property_location: '5501 Lakeview Dr, Kirkland, WA 98033',
        policy_number: 'HO-555001-01',
        date_issued: '2023-01-10',
        policy_period_start: '2023-01-15',
        policy_period_end: '2024-01-15',
        renewal_date: '2024-01-15',
        year_built: 1995,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Frame',
        deductible: '$2,500',
        limit_dwelling: '$850,000',
        limit_other_structures: '$85,000',
        limit_personal_property: '$425,000',
        limit_fair_rental_value: '$170,000',
        limit_ordinance_or_law: '$85,000',
        limit_debris_removal: '$42,500',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$5,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$10,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$1,950',
        broker_name: 'Lakeside Insurance',
        broker_address: 'Kirkland, WA',
        broker_phone_number: '(425) 555-0001',
        status: 'Approved',
        flags: [],
    },
    {
        id: '7',
        insured_name: 'Patricia Moore',
        mailing_address: '1010 Capital Blvd, Austin, TX 78701',
        property_location: '1010 Capital Blvd, Austin, TX 78701',
        policy_number: 'HO-555002-02',
        date_issued: '2023-02-14',
        policy_period_start: '2023-03-01',
        policy_period_end: '2024-03-01',
        renewal_date: '2024-03-01',
        year_built: 2021,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Masonry',
        deductible: '$5,000',
        limit_dwelling: '$1,100,000',
        limit_other_structures: '$110,000',
        limit_personal_property: '$550,000',
        limit_fair_rental_value: '$220,000',
        limit_ordinance_or_law: '$110,000',
        limit_debris_removal: '$55,000',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$10,000',
        limit_permitted_incidental_occupancy: '$5,000',
        limit_plants_shrubs_trees: '$20,000',
        limit_outdoor_radio_tv_equipment: '$2,000',
        limit_awnings: '$5,000',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$50',
        total_annual_premium: '$2,800',
        broker_name: 'Texas Shield',
        broker_address: 'Austin, TX',
        broker_phone_number: '(512) 555-0002',
        status: 'Pending Review',
        flags: ['High Value'],
    },
    {
        id: '8',
        insured_name: 'Robert Taylor',
        mailing_address: '250 Park Ave, New York, NY 10177',
        property_location: '250 Park Ave, New York, NY 10177',
        policy_number: 'HO-555003-03',
        date_issued: '2023-04-01',
        policy_period_start: '2023-04-15',
        policy_period_end: '2024-04-15',
        renewal_date: '2024-04-15',
        year_built: 1930,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Masonry',
        deductible: '$2,500',
        limit_dwelling: '$2,500,000',
        limit_other_structures: '$0',
        limit_personal_property: '$1,000,000',
        limit_fair_rental_value: '$500,000',
        limit_ordinance_or_law: '$250,000',
        limit_debris_removal: '$100,000',
        limit_extended_dwelling_coverage: '50%',
        limit_dwelling_replacement_cost: 'Guaranteed',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$0',
        limit_permitted_incidental_occupancy: '$10,000',
        limit_plants_shrubs_trees: '$0',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$5,200',
        broker_name: 'Gotham Insurance',
        broker_address: 'New York, NY',
        broker_phone_number: '(212) 555-0003',
        status: 'Approved',
        flags: ['High Value', 'Old Construction'],
    },
    {
        id: '9',
        insured_name: 'Jennifer Anderson',
        mailing_address: '888 Beach Blvd, San Diego, CA 92109',
        property_location: '888 Beach Blvd, San Diego, CA 92109',
        policy_number: 'HO-555004-04',
        date_issued: '2023-05-20',
        policy_period_start: '2023-06-01',
        policy_period_end: '2024-06-01',
        renewal_date: '2024-06-01',
        year_built: 1980,
        occupancy: 'Secondary',
        number_of_units: 1,
        construction_type: 'Frame',
        deductible: '$1,500',
        limit_dwelling: '$750,000',
        limit_other_structures: '$75,000',
        limit_personal_property: '$300,000',
        limit_fair_rental_value: '$150,000',
        limit_ordinance_or_law: '$75,000',
        limit_debris_removal: '$37,500',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$2,500',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$10,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$150',
        total_annual_premium: '$2,100',
        broker_name: 'Pacific Coast Ins',
        broker_address: 'San Diego, CA',
        broker_phone_number: '(619) 555-0004',
        status: 'Incomplete',
        flags: ['Secondary Residence'],
    },
    {
        id: '10',
        insured_name: 'Charles Thomas',
        mailing_address: '500 Mountain View, Denver, CO 80202',
        property_location: '500 Mountain View, Denver, CO 80202',
        policy_number: 'HO-555005-05',
        date_issued: '2023-07-05',
        policy_period_start: '2023-07-15',
        policy_period_end: '2024-07-15',
        renewal_date: '2024-07-15',
        year_built: 2015,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Frame',
        deductible: '$2,500',
        limit_dwelling: '$650,000',
        limit_other_structures: '$65,000',
        limit_personal_property: '$325,000',
        limit_fair_rental_value: '$130,000',
        limit_ordinance_or_law: '$65,000',
        limit_debris_removal: '$32,500',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$10,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$15,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$250',
        total_annual_premium: '$2,400',
        broker_name: 'Mountain High Brokers',
        broker_address: 'Denver, CO',
        broker_phone_number: '(303) 555-0005',
        status: 'Rejected',
        flags: ['Wildfire Zone', 'High Premium'],
    },
    {
        id: '11',
        insured_name: 'Linda Jackson',
        mailing_address: '1234 Main St, Anytown, USA 12345',
        property_location: '1234 Main St, Anytown, USA 12345',
        policy_number: 'HO-555006-06',
        date_issued: '2023-08-10',
        policy_period_start: '2023-08-15',
        policy_period_end: '2024-08-15',
        renewal_date: '2024-08-15',
        year_built: 1990,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Frame',
        deductible: '$1,000',
        limit_dwelling: '$400,000',
        limit_other_structures: '$40,000',
        limit_personal_property: '$200,000',
        limit_fair_rental_value: '$80,000',
        limit_ordinance_or_law: '$40,000',
        limit_debris_removal: '$20,000',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$2,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$5,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$1,200',
        broker_name: 'General Insure',
        broker_address: 'Anytown, USA',
        broker_phone_number: '(555) 555-0006',
        status: 'Approved',
        flags: [],
    },
    {
        id: '12',
        insured_name: 'Christopher White',
        mailing_address: '777 Casino Dr, Las Vegas, NV 89109',
        property_location: '777 Casino Dr, Las Vegas, NV 89109',
        policy_number: 'HO-555007-07',
        date_issued: '2023-09-01',
        policy_period_start: '2023-09-15',
        policy_period_end: '2024-09-15',
        renewal_date: '2024-09-15',
        year_built: 2005,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Stucco',
        deductible: '$2,500',
        limit_dwelling: '$550,000',
        limit_other_structures: '$55,000',
        limit_personal_property: '$275,000',
        limit_fair_rental_value: '$110,000',
        limit_ordinance_or_law: '$55,000',
        limit_debris_removal: '$27,500',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$5,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$5,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$1,650',
        broker_name: 'Desert Brokers',
        broker_address: 'Las Vegas, NV',
        broker_phone_number: '(702) 555-0007',
        status: 'Pending Review',
        flags: [],
    },
    {
        id: '13',
        insured_name: 'Barbara Harris',
        mailing_address: '808 Palm St, Honolulu, HI 96813',
        property_location: '808 Palm St, Honolulu, HI 96813',
        policy_number: 'HO-555008-08',
        date_issued: '2023-10-10',
        policy_period_start: '2023-11-01',
        policy_period_end: '2024-11-01',
        renewal_date: '2024-11-01',
        year_built: 1975,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Frame',
        deductible: '$1,500',
        limit_dwelling: '$900,000',
        limit_other_structures: '$90,000',
        limit_personal_property: '$450,000',
        limit_fair_rental_value: '$180,000',
        limit_ordinance_or_law: '$90,000',
        limit_debris_removal: '$45,000',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$5,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$15,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$2,900',
        broker_name: 'Aloha Insurance',
        broker_address: 'Honolulu, HI',
        broker_phone_number: '(808) 555-0008',
        status: 'Approved',
        flags: ['High Value'],
    },
    {
        id: '14',
        insured_name: 'Paul Martin',
        mailing_address: '600 Broadway, Nashville, TN 37203',
        property_location: '600 Broadway, Nashville, TN 37203',
        policy_number: 'HO-555009-09',
        date_issued: '2023-11-20',
        policy_period_start: '2023-12-01',
        policy_period_end: '2024-12-01',
        renewal_date: '2024-12-01',
        year_built: 2000,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Brick',
        deductible: '$2,000',
        limit_dwelling: '$500,000',
        limit_other_structures: '$50,000',
        limit_personal_property: '$250,000',
        limit_fair_rental_value: '$100,000',
        limit_ordinance_or_law: '$50,000',
        limit_debris_removal: '$25,000',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$3,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$5,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$1,400',
        broker_name: 'Music City Ins',
        broker_address: 'Nashville, TN',
        broker_phone_number: '(615) 555-0009',
        status: 'Approved',
        flags: [],
    },
    {
        id: '15',
        insured_name: 'Nancy Thompson',
        mailing_address: '999 Peachtree St, Atlanta, GA 30309',
        property_location: '999 Peachtree St, Atlanta, GA 30309',
        policy_number: 'HO-555010-10',
        date_issued: '2023-12-15',
        policy_period_start: '2024-01-01',
        policy_period_end: '2025-01-01',
        renewal_date: '2025-01-01',
        year_built: 1998,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Frame',
        deductible: '$1,500',
        limit_dwelling: '$475,000',
        limit_other_structures: '$47,500',
        limit_personal_property: '$237,500',
        limit_fair_rental_value: '$95,000',
        limit_ordinance_or_law: '$47,500',
        limit_debris_removal: '$23,750',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$2,500',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$7,500',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$1,350',
        broker_name: 'Peach State Ins',
        broker_address: 'Atlanta, GA',
        broker_phone_number: '(404) 555-0010',
        status: 'Incomplete',
        flags: ['Missing Info'],
    },
    {
        id: '16',
        insured_name: 'Timothy Clark',
        mailing_address: '222 Forest Ln, Portland, OR 97205',
        property_location: '222 Forest Ln, Portland, OR 97205',
        policy_number: 'HO-555011-11',
        date_issued: '2023-01-20',
        policy_period_start: '2023-02-01',
        policy_period_end: '2024-02-01',
        renewal_date: '2024-02-01',
        year_built: 2012,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Mixed',
        deductible: '$2,500',
        limit_dwelling: '$800,000',
        limit_other_structures: '$80,000',
        limit_personal_property: '$400,000',
        limit_fair_rental_value: '$160,000',
        limit_ordinance_or_law: '$80,000',
        limit_debris_removal: '$40,000',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$5,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$25,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$100',
        total_annual_premium: '$2,300',
        broker_name: 'Pacific Northwest Ins',
        broker_address: 'Portland, OR',
        broker_phone_number: '(503) 555-0011',
        status: 'Approved',
        flags: ['Wildfire Zone'],
    },
    {
        id: '17',
        insured_name: 'Sarah Lewis',
        mailing_address: '333 River Rd, Cincinnati, OH 45202',
        property_location: '333 River Rd, Cincinnati, OH 45202',
        policy_number: 'HO-555012-12',
        date_issued: '2023-03-10',
        policy_period_start: '2023-04-01',
        policy_period_end: '2024-04-01',
        renewal_date: '2024-04-01',
        year_built: 1960,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Brick',
        deductible: '$1,000',
        limit_dwelling: '$350,000',
        limit_other_structures: '$35,000',
        limit_personal_property: '$175,000',
        limit_fair_rental_value: '$70,000',
        limit_ordinance_or_law: '$35,000',
        limit_debris_removal: '$17,500',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'ACV Only',
        limit_fences: '$5,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$5,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$950',
        broker_name: 'River Valley Ins',
        broker_address: 'Cincinnati, OH',
        broker_phone_number: '(513) 555-0012',
        status: 'Pending Review',
        flags: ['Old Construction'],
    },
    {
        id: '18',
        insured_name: 'George Walker',
        mailing_address: '444 Desert Way, Phoenix, AZ 85001',
        property_location: '444 Desert Way, Phoenix, AZ 85001',
        policy_number: 'HO-555013-13',
        date_issued: '2023-05-15',
        policy_period_start: '2023-06-01',
        policy_period_end: '2024-06-01',
        renewal_date: '2024-06-01',
        year_built: 2008,
        occupancy: 'Secondary',
        number_of_units: 1,
        construction_type: 'Stucco',
        deductible: '$2,500',
        limit_dwelling: '$500,000',
        limit_other_structures: '$10,000',
        limit_personal_property: '$100,000',
        limit_fair_rental_value: '$50,000',
        limit_ordinance_or_law: '$50,000',
        limit_debris_removal: '$25,000',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$10,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$5,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$5,000',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: false,
        wildfire_premium: '$0',
        total_annual_premium: '$1,100',
        broker_name: 'Cactus State Ins',
        broker_address: 'Phoenix, AZ',
        broker_phone_number: '(602) 555-0013',
        status: 'Approved',
        flags: ['Secondary Residence'],
    },
    {
        id: '19',
        insured_name: 'Megan Hall',
        mailing_address: '555 Lake Dr, Chicago, IL 60601',
        property_location: '555 Lake Dr, Chicago, IL 60601',
        policy_number: 'HO-555014-14',
        date_issued: '2023-06-20',
        policy_period_start: '2023-07-01',
        policy_period_end: '2024-07-01',
        renewal_date: '2024-07-01',
        year_built: 1940,
        occupancy: 'Primary Residence',
        number_of_units: 3,
        construction_type: 'Brick',
        deductible: '$5,000',
        limit_dwelling: '$1,500,000',
        limit_other_structures: '$100,000',
        limit_personal_property: '$750,000',
        limit_fair_rental_value: '$300,000',
        limit_ordinance_or_law: '$150,000',
        limit_debris_removal: '$75,000',
        limit_extended_dwelling_coverage: '50%',
        limit_dwelling_replacement_cost: 'Guaranteed',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$10,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$10,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$4,500',
        broker_name: 'Windy City Brokers',
        broker_address: 'Chicago, IL',
        broker_phone_number: '(312) 555-0014',
        status: 'Pending Review',
        flags: ['High Value'],
    },
    {
        id: '20',
        insured_name: 'Anthony Allen',
        mailing_address: '666 Swamp Rd, New Orleans, LA 70112',
        property_location: '666 Swamp Rd, New Orleans, LA 70112',
        policy_number: 'HO-555015-15',
        date_issued: '2023-08-01',
        policy_period_start: '2023-08-15',
        policy_period_end: '2024-08-15',
        renewal_date: '2024-08-15',
        year_built: 1900,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Wood',
        deductible: '$5,000',
        limit_dwelling: '$400,000',
        limit_other_structures: '$40,000',
        limit_personal_property: '$200,000',
        limit_fair_rental_value: '$80,000',
        limit_ordinance_or_law: '$40,000',
        limit_debris_removal: '$20,000',
        limit_extended_dwelling_coverage: 'None',
        limit_dwelling_replacement_cost: 'Functional',
        limit_inflation_guard: 'None',
        limit_personal_property_replacement_cost: 'ACV Only',
        limit_fences: '$5,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$5,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$3,200',
        broker_name: 'Bayou Insurance',
        broker_address: 'New Orleans, LA',
        broker_phone_number: '(504) 555-0015',
        status: 'Rejected',
        flags: ['Old Construction', 'Flood Zone'],
    },
    {
        id: '21',
        insured_name: 'Lisa King',
        mailing_address: '777 Pine Ct, Raleigh, NC 27601',
        property_location: '777 Pine Ct, Raleigh, NC 27601',
        policy_number: 'HO-555016-16',
        date_issued: '2023-09-05',
        policy_period_start: '2023-09-15',
        policy_period_end: '2024-09-15',
        renewal_date: '2024-09-15',
        year_built: 2019,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Frame',
        deductible: '$1,500',
        limit_dwelling: '$550,000',
        limit_other_structures: '$55,000',
        limit_personal_property: '$275,000',
        limit_fair_rental_value: '$110,000',
        limit_ordinance_or_law: '$55,000',
        limit_debris_removal: '$27,500',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$5,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$10,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$1,300',
        broker_name: 'Carolina Insure',
        broker_address: 'Raleigh, NC',
        broker_phone_number: '(919) 555-0016',
        status: 'Approved',
        flags: [],
    },
    {
        id: '22',
        insured_name: 'Brian Wright',
        mailing_address: '888 Hilltop Rd, Denver, CO 80203',
        property_location: '888 Hilltop Rd, Denver, CO 80203',
        policy_number: 'HO-555017-17',
        date_issued: '2023-10-15',
        policy_period_start: '2023-11-01',
        policy_period_end: '2024-11-01',
        renewal_date: '2024-11-01',
        year_built: 1995,
        occupancy: 'Tenant',
        number_of_units: 2,
        construction_type: 'Frame',
        deductible: '$2,500',
        limit_dwelling: '$600,000',
        limit_other_structures: '$60,000',
        limit_personal_property: '$50,000',
        limit_fair_rental_value: '$30,000',
        limit_ordinance_or_law: '$30,000',
        limit_debris_removal: '$15,000',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'ACV Only',
        limit_fences: '$5,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$5,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$200',
        total_annual_premium: '$1,900',
        broker_name: 'Mile High Brokers',
        broker_address: 'Denver, CO',
        broker_phone_number: '(303) 555-0017',
        status: 'Incomplete',
        flags: ['Wildfire Zone'],
    },
    {
        id: '23',
        insured_name: 'Karen Scott',
        mailing_address: '999 Valley View, Salt Lake City, UT 84101',
        property_location: '999 Valley View, Salt Lake City, UT 84101',
        policy_number: 'HO-555018-18',
        date_issued: '2023-11-01',
        policy_period_start: '2023-11-15',
        policy_period_end: '2024-11-15',
        renewal_date: '2024-11-15',
        year_built: 2005,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Stucco',
        deductible: '$1,000',
        limit_dwelling: '$450,000',
        limit_other_structures: '$45,000',
        limit_personal_property: '$225,000',
        limit_fair_rental_value: '$90,000',
        limit_ordinance_or_law: '$45,000',
        limit_debris_removal: '$22,500',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$5,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$10,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$1,150',
        broker_name: 'Wasatch Insurance',
        broker_address: 'Salt Lake City, UT',
        broker_phone_number: '(801) 555-0018',
        status: 'Approved',
        flags: [],
    },
    {
        id: '24',
        insured_name: 'Kevin Young',
        mailing_address: '1212 Downtown St, Boston, MA 02108',
        property_location: '1212 Downtown St, Boston, MA 02108',
        policy_number: 'HO-555019-19',
        date_issued: '2023-12-05',
        policy_period_start: '2024-01-01',
        policy_period_end: '2025-01-01',
        renewal_date: '2025-01-01',
        year_built: 1920,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Brick',
        deductible: '$2,500',
        limit_dwelling: '$900,000',
        limit_other_structures: '$0',
        limit_personal_property: '$450,000',
        limit_fair_rental_value: '$180,000',
        limit_ordinance_or_law: '$90,000',
        limit_debris_removal: '$45,000',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$0',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$5,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$2,500',
        broker_name: 'New England Ins',
        broker_address: 'Boston, MA',
        broker_phone_number: '(617) 555-0019',
        status: 'Approved',
        flags: ['Old Construction'],
    },
    {
        id: '25',
        insured_name: 'Sandra Adams',
        mailing_address: '3434 Farm Rd, Des Moines, IA 50309',
        property_location: '3434 Farm Rd, Des Moines, IA 50309',
        policy_number: 'HO-555020-20',
        date_issued: '2023-12-20',
        policy_period_start: '2024-01-15',
        policy_period_end: '2025-01-15',
        renewal_date: '2025-01-15',
        year_built: 2010,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Frame',
        deductible: '$1,000',
        limit_dwelling: '$350,000',
        limit_other_structures: '$35,000',
        limit_personal_property: '$175,000',
        limit_fair_rental_value: '$70,000',
        limit_ordinance_or_law: '$35,000',
        limit_debris_removal: '$17,500',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$5,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$10,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$900',
        broker_name: 'Midwest Brokers',
        broker_address: 'Des Moines, IA',
        broker_phone_number: '(515) 555-0020',
        status: 'Pending Review',
        flags: [],
    },
    {
        id: '26',
        insured_name: 'Steven Baker',
        mailing_address: '5656 Sunny Ln, Miami, FL 33101',
        property_location: '5656 Sunny Ln, Miami, FL 33101',
        policy_number: 'HO-555021-21',
        date_issued: '2024-01-05',
        policy_period_start: '2024-01-10',
        policy_period_end: '2025-01-10',
        renewal_date: '2025-01-10',
        year_built: 2022,
        occupancy: 'Secondary',
        number_of_units: 1,
        construction_type: 'Concrete',
        deductible: '$5,000',
        limit_dwelling: '$1,500,000',
        limit_other_structures: '$150,000',
        limit_personal_property: '$750,000',
        limit_fair_rental_value: '$300,000',
        limit_ordinance_or_law: '$150,000',
        limit_debris_removal: '$75,000',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$10,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$25,000',
        limit_outdoor_radio_tv_equipment: '$5,000',
        limit_awnings: '$5,000',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$5,500',
        broker_name: 'Sunshine State Ins',
        broker_address: 'Miami, FL',
        broker_phone_number: '(305) 555-0021',
        status: 'Incomplete',
        flags: ['Secondary Residence', 'High Value', 'Windstorm'],
    },
    {
        id: '27',
        insured_name: 'Betty Green',
        mailing_address: '7878 Arctic Cir, Anchorage, AK 99501',
        property_location: '7878 Arctic Cir, Anchorage, AK 99501',
        policy_number: 'HO-555022-22',
        date_issued: '2024-01-15',
        policy_period_start: '2024-02-01',
        policy_period_end: '2025-02-01',
        renewal_date: '2025-02-01',
        year_built: 1985,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Frame',
        deductible: '$1,000',
        limit_dwelling: '$400,000',
        limit_other_structures: '$40,000',
        limit_personal_property: '$200,000',
        limit_fair_rental_value: '$80,000',
        limit_ordinance_or_law: '$40,000',
        limit_debris_removal: '$20,000',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$2,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$5,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$1,800',
        broker_name: 'Northern Lights Ins',
        broker_address: 'Anchorage, AK',
        broker_phone_number: '(907) 555-0022',
        status: 'Approved',
        flags: [],
    },
    {
        id: '28',
        insured_name: 'Daniel Nelson',
        mailing_address: '9090 Redwood Dr, San Jose, CA 95110',
        property_location: '9090 Redwood Dr, San Jose, CA 95110',
        policy_number: 'HO-555023-23',
        date_issued: '2024-02-01',
        policy_period_start: '2024-02-15',
        policy_period_end: '2025-02-15',
        renewal_date: '2025-02-15',
        year_built: 1970,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Frame',
        deductible: '$2,000',
        limit_dwelling: '$1,200,000',
        limit_other_structures: '$120,000',
        limit_personal_property: '$600,000',
        limit_fair_rental_value: '$240,000',
        limit_ordinance_or_law: '$120,000',
        limit_debris_removal: '$60,000',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$15,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$20,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$100',
        total_annual_premium: '$2,600',
        broker_name: 'Silicon Valley Brokers',
        broker_address: 'San Jose, CA',
        broker_phone_number: '(408) 555-0023',
        status: 'Approved',
        flags: ['High Value'],
    },
    {
        id: '29',
        insured_name: 'Michelle Carter',
        mailing_address: '1212 Bourbon St, New Orleans, LA 70116',
        property_location: '1212 Bourbon St, New Orleans, LA 70116',
        policy_number: 'HO-555024-24',
        date_issued: '2024-02-10',
        policy_period_start: '2024-03-01',
        policy_period_end: '2025-03-01',
        renewal_date: '2025-03-01',
        year_built: 1890,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Brick',
        deductible: '$5,000',
        limit_dwelling: '$650,000',
        limit_other_structures: '$65,000',
        limit_personal_property: '$325,000',
        limit_fair_rental_value: '$130,000',
        limit_ordinance_or_law: '$65,000',
        limit_debris_removal: '$32,500',
        limit_extended_dwelling_coverage: 'None',
        limit_dwelling_replacement_cost: 'Functional',
        limit_inflation_guard: 'None',
        limit_personal_property_replacement_cost: 'ACV Only',
        limit_fences: '$2,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$5,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$0',
        total_annual_premium: '$4,000',
        broker_name: 'French Quarter Ins',
        broker_address: 'New Orleans, LA',
        broker_phone_number: '(504) 555-0024',
        status: 'Pending Review',
        flags: ['Old Construction'],
    },
    {
        id: '30',
        insured_name: 'Thomas Mitchell',
        mailing_address: '3333 Elk Rd, Helena, MT 59601',
        property_location: '3333 Elk Rd, Helena, MT 59601',
        policy_number: 'HO-555025-25',
        date_issued: '2024-03-01',
        policy_period_start: '2024-03-15',
        policy_period_end: '2025-03-15',
        renewal_date: '2025-03-15',
        year_built: 2000,
        occupancy: 'Primary Residence',
        number_of_units: 1,
        construction_type: 'Log',
        deductible: '$2,500',
        limit_dwelling: '$750,000',
        limit_other_structures: '$75,000',
        limit_personal_property: '$375,000',
        limit_fair_rental_value: '$150,000',
        limit_ordinance_or_law: '$75,000',
        limit_debris_removal: '$37,500',
        limit_extended_dwelling_coverage: '25%',
        limit_dwelling_replacement_cost: 'Included',
        limit_inflation_guard: 'Included',
        limit_personal_property_replacement_cost: 'Included',
        limit_fences: '$10,000',
        limit_permitted_incidental_occupancy: '$0',
        limit_plants_shrubs_trees: '$10,000',
        limit_outdoor_radio_tv_equipment: '$0',
        limit_awnings: '$0',
        limit_signs: '$0',
        cb_fire_lightning_smoke_damage: true,
        cb_extended_coverages: true,
        cb_vandalism_malicious_mischief: true,
        wildfire_premium: '$300',
        total_annual_premium: '$2,800',
        broker_name: 'Big Sky Brokers',
        broker_address: 'Helena, MT',
        broker_phone_number: '(406) 555-0025',
        status: 'Approved',
        flags: ['Wildfire Zone'],
    }
];

export async function fetchDeclarations(): Promise<Declaration[]> {
    return mockData;
}

export async function getDeclarationById(id: string): Promise<Declaration | undefined> {
    return mockData.find(d => d.id === id);
}

export interface AIReportData {
    coverageGaps: string[];
    flags: string[];
    suggestions: string[];
}

export async function fetchAIReport(id: string): Promise<AIReportData> {
    // Mock AI generation
    return {
        coverageGaps: [
            'Missing Extended Replacement Cost Coverage',
            'No Earthquake Coverage',
            'Umbrella Policy recommended for high net worth'
        ],
        flags: [
            'Property in High Wildfire Zone',
            'Roof age > 15 years',
            'Inflation Guard is lower than recommended'
        ],
        suggestions: [
            'Increase Ordinance or Law coverage to 50%',
            'Review personal property limits (currently low relative to dwelling)',
            'Add Service Line Coverage'
        ]
    };
}
